# ASP.NET Core (.NET Framework)
# Build and test ASP.NET Core projects targeting the full .NET Framework.
# Add steps that publish symbols, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core
resources:
- repo: self
queue:
  name: Hosted VS2017
  demands: 
  - msbuild
  - vstest

steps:
- task: NuGetToolInstaller@0

- task: NuGetCommand@2
  inputs:
    restoreSolution: '$(Parameters.solution)'

- task: MSBuild@1
  inputs:
    platform: '$(BuildPlatform)'
    configuration: '$(buildConfiguration)'

- task: VSTest@2
  inputs:
    testAssemblyVer2: |
     **\bin\$(BuildConfiguration)\*UnitTestProject1*.dll
     **\bin\$(BuildConfiguration)\*UnitTestProject1*.dll
    codeCoverageEnabled: true
    platform: '$(BuildPlatform)'
    configuration: '$(BuildConfiguration)'
